/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemaestoque;
// Importações de funcionalidade
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

// Importações para o PDF (iText)
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

// Importações para abrir o arquivo PDF
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
/**
 *
 * @author bruno
 */
public class TelaPrincipal extends javax.swing.JFrame {
    private ProdutoDAO produtoDAO;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();

    // Adicione estas 3 linhas:
    setLocationRelativeTo(null); // Centraliza a janela
    this.produtoDAO = new ProdutoDAO(); // Inicializa o DAO
    preencherTabela(); // Carrega os dados do banco na tabela
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jBadd = new javax.swing.JButton();
        jBeditar = new javax.swing.JButton();
        jBexcluir = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnMostrarTodos = new javax.swing.JButton();
        btnGerarPDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "Descrição", "Qtd", "Preço", "Fornecedor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jBadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemaestoque/icons8-add-24.png"))); // NOI18N
        jBadd.setToolTipText("Adicionar Novo Produto");
        jBadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaddActionPerformed(evt);
            }
        });

        jBeditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemaestoque/icons8-edit-24.png"))); // NOI18N
        jBeditar.setToolTipText("Editar Produto Selecionado");
        jBeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeditarActionPerformed(evt);
            }
        });

        jBexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemaestoque/icons8-delete-24.png"))); // NOI18N
        jBexcluir.setToolTipText("Excluir Produto Selecionado");
        jBexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexcluirActionPerformed(evt);
            }
        });

        jBSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemaestoque/icons8-logout-24.png"))); // NOI18N
        jBSair.setToolTipText("Sair do Sistema");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        jLabel1.setText("Pesquisar por Nome:");

        txtBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnMostrarTodos.setText("MostrarTodos");
        btnMostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodosActionPerformed(evt);
            }
        });

        btnGerarPDF.setText("GerarPDF");
        btnGerarPDF.setToolTipText("Gerar relatório de estoque em PDF");
        btnGerarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBadd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBeditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBexcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBSair)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnGerarPDF)
                                .addComponent(btnMostrarTodos)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(btnBuscar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBadd)
                    .addComponent(jBeditar)
                    .addComponent(jBexcluir)
                    .addComponent(jBSair))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrarTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGerarPDF)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaddActionPerformed
        TelaCadastroProduto telaCadastro = new TelaCadastroProduto(this, true, null);
        telaCadastro.setVisible(true);
        preencherTabela();
    }//GEN-LAST:event_jBaddActionPerformed

    private void jBeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeditarActionPerformed
       int linhaSelecionada = jTable2.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um produto para editar.");
            return;
        }
        int idProduto = (int) jTable2.getValueAt(linhaSelecionada, 0);
        Produto produtoParaEditar = new Produto();
        produtoParaEditar.setId(idProduto);
        TelaCadastroProduto telaCadastro = new TelaCadastroProduto(this, true, produtoParaEditar);
        telaCadastro.setVisible(true);
        preencherTabela();
    }//GEN-LAST:event_jBeditarActionPerformed

    private void jBexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexcluirActionPerformed
       int linhaSelecionada = jTable2.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um produto para excluir.");
            return;
        }
        int idProduto = (int) jTable2.getValueAt(linhaSelecionada, 0);
        int confirmacao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir este produto?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (confirmacao == JOptionPane.YES_OPTION) {
            produtoDAO.excluir(idProduto);
            preencherTabela();
        }
    }//GEN-LAST:event_jBexcluirActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
       int resposta = JOptionPane.showConfirmDialog(
            this, "Tem certeza que deseja sair do sistema?", "Confirmação de Saída", JOptionPane.YES_NO_OPTION
        );
        if (resposta == JOptionPane.YES_OPTION) { System.exit(0); }
    }//GEN-LAST:event_jBSairActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       String nomeParaBusca = txtBusca.getText();
        List<Produto> resultados = produtoDAO.buscarPorNome(nomeParaBusca);
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
        modelo.setNumRows(0);
        for (Produto p : resultados) {
            modelo.addRow(new Object[]{
                p.getId(), p.getNome(), p.getDescricao(), p.getQuantidade(), p.getPreco(), p.getFornecedor()
            });
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodosActionPerformed
        txtBusca.setText("");
        preencherTabela();
    }//GEN-LAST:event_btnMostrarTodosActionPerformed

    private void btnGerarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarPDFActionPerformed
       String nomeArquivo = "relatorio_estoque_completo.pdf";
        Document documento = new Document(PageSize.A4);
        
        try {
            PdfWriter.getInstance(documento, new FileOutputStream(nomeArquivo));
            documento.open();
            
            // --- PARTE 1: TÍTULO GERAL ---
            Font fonteTitulo = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD);
            Font fonteSubtitulo = new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD);
            Font fonteCabecalho = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
            
            Paragraph titulo = new Paragraph("Relatório Geral de Estoque", fonteTitulo);
            titulo.setAlignment(Element.ALIGN_CENTER);
            documento.add(titulo);
            documento.add(new Paragraph(" ")); // Espaço em branco
            
            // ==========================================
            // --- PARTE 2: TABELA DE PRODUTOS ATUAIS ---
            // ==========================================
            documento.add(new Paragraph("Posição Atual do Estoque", fonteSubtitulo));
            documento.add(new Paragraph(" ")); // Espaço
            
            PdfPTable tabelaProdutos = new PdfPTable(6); // 6 Colunas
            tabelaProdutos.setWidthPercentage(100);
            
            // Cabeçalho Produtos
            tabelaProdutos.addCell(new PdfPCell(new Phrase("ID", fonteCabecalho)));
            tabelaProdutos.addCell(new PdfPCell(new Phrase("Nome", fonteCabecalho)));
            tabelaProdutos.addCell(new PdfPCell(new Phrase("Descrição", fonteCabecalho)));
            tabelaProdutos.addCell(new PdfPCell(new Phrase("Qtd", fonteCabecalho)));
            tabelaProdutos.addCell(new PdfPCell(new Phrase("Preço", fonteCabecalho)));
            tabelaProdutos.addCell(new PdfPCell(new Phrase("Fornecedor", fonteCabecalho)));
            
            // Dados Produtos
            List<Produto> listaProdutos = produtoDAO.listar();
            for (Produto p : listaProdutos) {
                tabelaProdutos.addCell(String.valueOf(p.getId()));
                tabelaProdutos.addCell(p.getNome());
                tabelaProdutos.addCell(p.getDescricao());
                tabelaProdutos.addCell(String.valueOf(p.getQuantidade()));
                tabelaProdutos.addCell(p.getPreco().toPlainString());
                tabelaProdutos.addCell(p.getFornecedor() != null ? p.getFornecedor() : "");
            }
            documento.add(tabelaProdutos);
            
            // Espaço grande entre as tabelas
            documento.add(new Paragraph(" ")); 
            documento.add(new Paragraph(" ")); 
            
            // ==========================================
            // --- PARTE 3: TABELA DE MOVIMENTAÇÕES ---
            // ==========================================
            documento.add(new Paragraph("Histórico de Entradas e Saídas", fonteSubtitulo));
            documento.add(new Paragraph(" ")); // Espaço
            
            PdfPTable tabelaMov = new PdfPTable(4); // 4 Colunas (Produto, Tipo, Qtd, Data)
            tabelaMov.setWidthPercentage(100);
            
            // Cabeçalho Movimentações
            tabelaMov.addCell(new PdfPCell(new Phrase("Produto", fonteCabecalho)));
            tabelaMov.addCell(new PdfPCell(new Phrase("Tipo", fonteCabecalho)));
            tabelaMov.addCell(new PdfPCell(new Phrase("Qtd", fonteCabecalho)));
            tabelaMov.addCell(new PdfPCell(new Phrase("Data/Hora", fonteCabecalho)));
            
            // Dados Movimentações (Buscando do novo DAO)
            MovimentacaoDAO movDAO = new MovimentacaoDAO();
            List<String[]> listaMov = movDAO.listarParaRelatorio();
            
            for (String[] mov : listaMov) {
                tabelaMov.addCell(mov[0]); // Nome do Produto
                tabelaMov.addCell(mov[1]); // Tipo (ENTRADA/SAIDA)
                tabelaMov.addCell(mov[2]); // Quantidade
                tabelaMov.addCell(mov[3]); // Data Formatada
            }
            documento.add(tabelaMov);
            
            // --- FIM ---
            JOptionPane.showMessageDialog(this, "Relatório completo gerado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            
            try {
                Desktop.getDesktop().open(new File(nomeArquivo));
            } catch (IOException e) {
                 JOptionPane.showMessageDialog(this, "PDF salvo, mas não abriu automaticamente.", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
            
        } catch (DocumentException | FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Erro ao gerar PDF: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        } finally {
            if (documento.isOpen()) {
                documento.close();
            }
        }
   
    }//GEN-LAST:event_btnGerarPDFActionPerformed

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaActionPerformed

    public void preencherTabela() {
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
        modelo.setNumRows(0);
        List<Produto> produtos = produtoDAO.listar();
        for (Produto p : produtos) {
            modelo.addRow(new Object[]{
                p.getId(), p.getNome(), p.getDescricao(), p.getQuantidade(), p.getPreco(),p.getFornecedor()
            });
        }
    }
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGerarPDF;
    private javax.swing.JButton btnMostrarTodos;
    private javax.swing.JButton jBSair;
    private javax.swing.JButton jBadd;
    private javax.swing.JButton jBeditar;
    private javax.swing.JButton jBexcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
